// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using patient_api.Data;

#nullable disable

namespace patient_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("patient_api.Models.Patient", b =>
                {
                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("row_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RowId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FirstName");

                    b.Property<string>("KmedId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("KmedID");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LastName");

                    b.Property<decimal?>("MobileNo")
                        .HasPrecision(18)
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("mobile_no");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password");

                    b.Property<int?>("PatientStatus")
                        .HasColumnType("int")
                        .HasColumnName("Patient_Status");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("user_id");

                    b.HasKey("RowId");

                    b.ToTable("Patient", "dbo", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("patient_api.Models.PatientAuthState", b =>
                {
                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LockedUntilUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.HasKey("PatientId");

                    b.ToTable("PatientAuthState", "dbo");
                });

            modelBuilder.Entity("patient_api.Models.PatientTaskLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("date");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("SubmittedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TaskKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("PatientId", "LogDate", "TaskKey")
                        .IsUnique();

                    b.ToTable("PatientTaskLog", "dbo");
                });

            modelBuilder.Entity("patient_api.Models.Visit", b =>
                {
                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("row_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RowId"));

                    b.Property<int>("DoctorId")
                        .HasColumnType("int")
                        .HasColumnName("doctor_id");

                    b.Property<bool?>("IsVisitOver")
                        .HasColumnType("bit")
                        .HasColumnName("is_visit_over");

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("patient_id");

                    b.Property<int>("PracticeId")
                        .HasColumnType("int")
                        .HasColumnName("practice_id");

                    b.Property<string>("PracticeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("practice_name");

                    b.Property<DateTime>("VisitOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("visit_on");

                    b.HasKey("RowId");

                    b.ToTable("Visit", "dbo", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("patient_api.Models.VitalSign", b =>
                {
                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("row_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RowId"));

                    b.Property<int?>("BloodPressureDiastolic")
                        .HasColumnType("int")
                        .HasColumnName("blood_pressure_distolic");

                    b.Property<int?>("BloodPressureSystolic")
                        .HasColumnType("int")
                        .HasColumnName("blood_pressure_systolic");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("date");

                    b.Property<decimal?>("Height")
                        .HasPrecision(22, 2)
                        .HasColumnType("decimal(22,2)")
                        .HasColumnName("height");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ip_address");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("patient_id");

                    b.Property<int?>("Pulse")
                        .HasColumnType("int")
                        .HasColumnName("pulse");

                    b.Property<int?>("RespiratoryRate")
                        .HasColumnType("int")
                        .HasColumnName("respiratory_rate");

                    b.Property<decimal?>("Spo2")
                        .HasPrecision(18)
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("spo2");

                    b.Property<decimal?>("Temperature")
                        .HasPrecision(22, 2)
                        .HasColumnType("decimal(22,2)")
                        .HasColumnName("temperature");

                    b.Property<int>("VisitId")
                        .HasColumnType("int")
                        .HasColumnName("visit_id");

                    b.Property<int?>("Weight")
                        .HasColumnType("int")
                        .HasColumnName("weight");

                    b.HasKey("RowId");

                    b.ToTable("VitalSign", "dbo", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("patient_api.Models.PatientAuthState", b =>
                {
                    b.HasOne("patient_api.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("patient_api.Models.PatientTaskLog", b =>
                {
                    b.HasOne("patient_api.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });
#pragma warning restore 612, 618
        }
    }
}
